const QUESTIONS = [
    { id: 1, text: "Az 1 KW nagyobb teljesítmény mint 1 lóerő.", fact: true, explain: "1 lóerő 0,75 KW", level: 2 },
    { id: 2, text: "A naprendszerben minden bolygónak van holdja.", fact: false, explain: "A Merkúrnak és a Vénusznak nincs.", level: 2 },
    { id: 3, text: "A Pi és a négyzetgyökkettő is komkrét, pontos szám.", fact: false, explain: "Mindegyik végtelen tört", level: 2 },
    { id: 4, text: "Minden rovar bogár, de nem minden bogár rovar.", fact: false, explain: "Fordítva", level: 2 },
    { id: 5, text: "Az Atmoszféra az SI rendszerben a nyomás mérték egysége.", fact: false, explain: "Bar, Pascal", level: 2 },
    { id: 6, text: "A föld kerületi sebessége az egyenlítőn meghaladja a hang sebességét.", fact: true, explain: "1600 km/h vs 1200 km/h", level: 2 },
    { id: 7, text: "A latin és a ciril betüket használó írásmódokban egyaránt arab számokat használnak.", fact: true, explain: "", level: 2 },
    { id: 8, text: "Kanada fővárosa Torontó.", fact: false, explain: "Kanada fővárosa Ottawa.", level: 2 },
    { id: 9, text: "A Himnuszt Erkel Ferenc 1844-ben írta.", fact: false, explain: "Kölcsey írta 1823-ban, Erkel megzenésítette 1844-ben.", level: 2 },
    { id: 10, text: "A kacsacsőrű emlős tojásokkal szaporodik, tejjel táplálja az utódait és nincs mérge.", fact: false, explain: "Van mérge.", level: 2 },
    { id: 11, text: "Minden elevenszülő álat emlős.", fact: false, explain: "Akár hal is lehet elevenszülő. PL: Cápa", level: 2 },
    { id: 12, text: "Több Mandarin anyanyelvű ember él mint Angol.", fact: true, explain: "A mandarin nyelvet nagyjából 2,4× annyi anyanyelvi beszélővel rendelkezik, mint az angol", level: 2 },
    { id: 13, text: "Egy 1cm és egy 1m sugarú körnek a kerülete azonos számú pontot tartalmaz.", fact: true, explain: "Mindegyik végtelen pontot tartalmaz.", level: 2 },
    { id: 14, text: "Már az ókorban is lézezett a Gőzgép.", fact: true, explain: "Aeolipile, Heron labdája Kru. 1. század.", level: 2 },
    { id: 15, text: "Bármely felületen kijelőlt háromszög szögeinek az összesége 180 fok.", fact: false, explain: "Csak síkon 180°, gömbön több.", level: 2 },
    { id: 16, text: "Siófokhoz közelebb van a legközelebbi vulkán, mint a legközelebbi gleccser.", fact: true, explain: "Badacsony is egy vulkán.", level: 2 },
    { id: 17, text: "Semmi sem mozoghat gyorsabban mint a fény.", fact: false, explain: "Maga a tér mozoghat/tágulhat gyorsabban.", level: 2 },
    { id: 18, text: "A legrégebbi ismert civilizáció a 6000 éves mezopotámiai civilizáció.", fact: false, explain: "Ma már ismert a kb 12000 éves Göpekli Tepe.", level: 2 },
    { id: 19, text: "Michalengaló, Mona Lisa festménye a párizsi Louvre-ban van kiállítva.", fact: false, explain: "A Mona Lisa Leonardo da Vinci alkotása.", level: 2 },
    { id: 20, text: "Egyetlen sejt, akár 1,5 kg is lehet.", fact: true, explain: "Strucc tojás.", level: 2 },
    { id: 21, text: "Az emberi szem látótávolsága akár több milliárd fényév is lehet.", fact: true, explain: "Ha van kellően erős fényforrás.", level: 2 },
    { id: 22, text: "A testsúlyom a föld nem minden pontján azonos.", fact: false, explain: "Egyenlítőn kevesebb, sarkokon több.", level: 2 },
    { id: 23, text: "A Kinai nagy fal hosszabb, mint a Budapest–Sydney távolság.", fact: true, explain: "A nagy fal sok helyen hegygerinc.", level: 2 },
    { id: 24, text: "Azonos teljesítmény esetén az áramerősség és a feszültség egyenesen arányos.", fact: false, explain: "Fordítva igaz.", level: 2 },
    { id: 25, text: "A kaméleonok nem a környezetük színe miatt változtatják a színüket.", fact: true, explain: "Hangulat, hőmérséklet, kommunikáció.", level: 2 },
    { id: 26, text: "A világ legnagyobb óceánja több mint a Föld felszínének egyharmadát lefedi.", fact: true, explain: "A Csendes-óceán ~33%.", level: 2 },
    { id: 27, text: "A méhek képesek repülés közben aludni.", fact: false, explain: "Csak kaptárban pihennek.", level: 2 },
    { id: 28, text: "A Földön több csirke él, mint ahány ember.", fact: true, explain: "25–33 milliárd csirke vs 8 milliárd ember.", level: 2 },
    { id: 29, text: "A Naprendszer legnagyobb vulkánja nem a Földön található.", fact: true, explain: "Olympus Mons a Marson.", level: 2 },
    { id: 30, text: "A világon több ország zászlajában szerepel a piros szín.", fact: true, explain: "A piros ~75%-ban jelen van.", level: 2 },
    { id: 31, text: "A Földön a legnagyobb élő madár a kondorkeselyű.", fact: false, explain: "A strucc a legnagyobb.", level: 2 },
    { id: 32, text: "A Jupiternek több mint 50 holdja van.", fact: true, explain: "92 ismert hold.", level: 2 },
    { id: 33, text: "A világon a legtöbb vulkán Indonéziában található.", fact: true, explain: "~130 aktív vulkán.", level: 2 },
    { id: 34, text: "A Föld mágneses pólusai időnként helyet cserélnek.", fact: true, explain: "Geomágneses pólusváltás.", level: 2 },
    { id: 35, text: "A világ legnagyobb szigete Ausztrália.", fact: false, explain: "Ausztrália kontinens, a legnagyobb sziget Grönland.", level: 2 },
    { id: 36, text: "A Föld légkörének több mint 20%-a oxigén.", fact: true, explain: "~21% oxigén.", level: 2 },
    { id: 37, text: "A világ leggyorsabb szárazföldi állata a gepárd.", fact: true, explain: "100–120 km/h.", level: 2 },
    { id: 38, text: "A Földön a legtöbb édesvíz a folyókban található.", fact: false, explain: "A folyók csak ~0,01%-ot tartalmaznak.", level: 2 },
    { id: 39, text: "A Holdon nincsenek szelek.", fact: true, explain: "Nincs légkör → nincs szél.", level: 2 },
    { id: 40, text: "A modern olimpián voltak művészeti versenyszámok.", fact: true, explain: "1912–1948 között.", level: 2 },
    { id: 41, text: "A világon a legtöbb ember anyanyelve a spanyol.", fact: false, explain: "A mandarin vezet.", level: 2 },
    { id: 42, text: "Keanu Reeves a kaszkadőrmutatványainak 70%-át maga csinálja.", fact: true, explain: "John Wick, Mátrix harcok.", level: 2 },
    { id: 43, text: "Einstein soha nem kapott Nobel-díjat a relativitáselméletért.", fact: true, explain: "A fotoelektromos effektusért kapta.", level: 2 },
    { id: 44, text: "Shakespeare műveinek több mint fele nem tőle származik.", fact: true, explain: "Szerzőségi vita.", level: 2 },
    { id: 45, text: "A koalák ujjlenyomata összekeverhető az emberével.", fact: true, explain: "Volt kriminalisztikai tévedés.", level: 2 },
    { id: 46, text: "A Wi-Fi nem a 'wireless fidelity' rövidítése.", fact: true, explain: "Marketingnév.", level: 2 },
    { id: 47, text: "A cápák idősebbek, mint a fák.", fact: true, explain: "Cápák ~420M év, fák ~385M év.", level: 2 },
    { id: 48, text: "A Vénuszon egy nap hosszabb, mint egy év.", fact: true, explain: "243 napos forgás, 225 napos keringés.", level: 2 },
    { id: 49, text: "A madarak a dinoszauruszok leszármazottai.", fact: true, explain: "Theropoda dinoszauruszok.", level: 2 },
    { id: 50, text: "A Holdon a lábnyomok ma is látszanak.", fact: true, explain: "Nincs erózió.", level: 2 },
    { id: 51, text: "A banán DNS-ének több mint 50%-a megegyezik az emberével.", fact: true, explain: "~50–60% egyezés.", level: 2 },
    { id: 52, text: "A víz akár 0 °C-on is felforrhat.", fact: true, explain: "Vákuumban hidegen is forr.", level: 2 },
    { id: 53, text: "A polipoknak három szívük van, és kék a vérük.", fact: true, explain: "Hemocianin, 3 szív.", level: 2 },
    { id: 54, text: "A hang a vízben akár ötször gyorsabban terjed.", fact: true, explain: "1480 m/s vs 343 m/s.", level: 2 },
    { id: 55, text: "A repülőgépek 'fekete doboza' valójában narancssárga.", fact: true, explain: "Könnyebb megtalálhatóság.", level: 2 },
    { id: 56, text: "A Szahara sivatagban esett már hó.", fact: true, explain: "2018, 2021.", level: 2 },
    { id: 57, text: "A méz korlátlan ideig eltartható.", fact: true, explain: "Egyiptomi sírokban is ehető volt.", level: 2 },

    { id: 58, text: "Az Eiffel-torony nyáron magasabb.", fact: true, explain: "Hőtágulás miatt akár 15 cm.", level: 2 },
    { id: 59, text: "Az oroszlánok főként éjszaka vadásznak.", fact: true, explain: "Sötétben nagyobb esély.", level: 2 },
    { id: 60, text: "A hangyák akár 50× saját súlyukat elbírják.", fact: true, explain: "Izomkeresztmetszet arány.", level: 2 },
    { id: 61, text: "A Vatikán a világ legkisebb állama.", fact: true, explain: "0,49 km².", level: 2 },
    { id: 62, text: "A zsiráfoknak ugyanannyi nyakcsigolyájuk van, mint az embernek.", fact: true, explain: "Mindkettő 7.", level: 2 },
    { id: 63, text: "A Csendes-óceán szélesebb, mint a Hold átmérője.", fact: true, explain: "19800 km vs 3474 km.", level: 2 },
    { id: 64, text: "A tigrisek csíkozata a bőrükön is látszik.", fact: true, explain: "Borotválva is látszik.", level: 2 },
    { id: 65, text: "A gitárnak és a hegedűnek ugyanannyi húrja van.", fact: false, explain: "Gitár 6, hegedű 4.", level: 2 },
    { id: 66, text: "A második világháború a legtöbb áldozatot követelte.", fact: true, explain: "70–85 millió halott.", level: 2 },
    { id: 67, text: "Magyarország a világ egyik legnagyobb hévízkincsével rendelkezik.", fact: true, explain: "Kárpát-medence termálvíz.", level: 2 },
    { id: 68, text: "Zeusz az istenek királya.", fact: true, explain: "Olümposz ura.", level: 2 },
    { id: 69, text: "Usain Bolt a 100m világcsúcstartója.", fact: true, explain: "9,58 mp (2009).", level: 2 },
    { id: 70, text: "A magyar nyelv az uráli nyelvcsaládba tartozik.", fact: true, explain: "Finnugor ág.", level: 2 },
    { id: 71, text: "A Tejútrendszerben található csillagok száma kevesebb, mint a Föld népessége.", fact: false, explain: "100–400 milliárd csillag.", level: 2 },
    { id: 72, text: "Mozart gyermekként már komponált zeneműveket.", fact: true, explain: "Már 5 évesen komponált.", level: 2 },
    { id: 73, text: "A vízilovak az egyik legveszélyesebb nagytestű állatok Afrikában.", fact: true, explain: "Több embert ölnek, mint az oroszlánok.", level: 2 },
    { id: 74, text: "A Facebook eredeti neve 'TheFacebook' volt.", fact: true, explain: "2004-ben indult ezen a néven.", level: 2 },
    { id: 75, text: "Napóleon alacsony termetű volt.", fact: false, explain: "168–170 cm, korának átlagos magassága.", level: 2 },
    { id: 76, text: "A Nagy Fal az egyetlen építmény, amely látható az űrből.", fact: false, explain: "Tévhit, nem látható szabad szemmel.", level: 2 },
    { id: 77, text: "Albert Einstein megbukott matematikából.", fact: false, explain: "Kiváló volt matematikából.", level: 2 },
    { id: 78, text: "A struccok a fejüket a homokba dugják.", fact: false, explain: "Tévhit, csak lehajtják a fejüket.", level: 2 },
    { id: 79, text: "A vörös bort szobahőmérsékleten kell fogyasztani.", fact: false, explain: "Ideális: 13–18°C.", level: 2 },
    { id: 80, text: "A vikingek szarvas sisakot viseltek.", fact: false, explain: "19. századi tévhit.", level: 2 },
    { id: 81, text: "A kaméleonok a környezetük színe miatt váltanak színt.", fact: false, explain: "Hangulat, hőmérséklet, kommunikáció.", level: 2 },
    { id: 82, text: "A Mount Everest a legmagasabb hegy a hegy alapjától mérve.", fact: false, explain: "A Mauna Kea magasabb az alapjától.", level: 2 },
    { id: 83, text: "A denevérek vakok.", fact: false, explain: "A legtöbb faj jól lát.", level: 2 },
    { id: 84, text: "A Kínai Nagy Falat a Csin-dinasztia építette teljes egészében.", fact: false, explain: "A Ming-dinasztia építette a legtöbb szakaszt.", level: 2 },
    { id: 85, text: "A Csendes-óceán a legmélyebb óceán is.", fact: true, explain: "Mariana-árok ~11 000 m.", level: 2 },
    { id: 86, text: "Marie Curie két különböző tudományterületen nyert Nobel-díjat.", fact: true, explain: "Fizika (1903), kémia (1911).", level: 2 },
    { id: 87, text: "A La Manche csatorna Európa és Amerika között húzódik.", fact: false, explain: "Nagy-Britannia és Franciaország között.", level: 2 },
    { id: 88, text: "A méhek elveszítik a fullánkjukat szúrás után.", fact: true, explain: "A fullánk beleakad és kiszakad.", level: 2 },
    { id: 89, text: "A Titanic elsüllyedésekor több túlélő volt, mint áldozat.", fact: false, explain: "1500 halott, ~700 túlélő.", level: 2 },
    { id: 90, text: "A gepárd hosszú távon is képes tartani a 120 km/h sebességet.", fact: false, explain: "Csak 20–30 másodpercig.", level: 2 },
    { id: 91, text: "Ausztrália egy teljes kontinenst lefedő ország.", fact: true, explain: "Egyedüli ilyen ország.", level: 2 },
    { id: 92, text: "A Beatles soha nem oszlott fel hivatalosan.", fact: false, explain: "1970-ben hivatalosan feloszlott.", level: 2 },
    { id: 93, text: "A Szaturnusz úszna a vízen.", fact: true, explain: "Átlagsűrűsége kisebb a víznél.", level: 2 },
    { id: 94, text: "A Nílus hosszabb, mint az Amazonas.", fact: true, explain: "6650 km vs 6400 km.", level: 2 },
    { id: 95, text: "A Sixtus-kápolna mennyezetét Leonardo da Vinci festette.", fact: false, explain: "Michelangelo festette.", level: 2 },
    { id: 96, text: "A koffein a legelterjedtebb pszichoaktív anyag.", fact: true, explain: "A világ 80%-a fogyasztja.", level: 2 },
    { id: 97, text: "Rubik Ernő matematikus volt.", fact: false, explain: "Építész és formatervező.", level: 2 },
    { id: 98, text: "A Galápagos-óriásteknősök 250 évig élnek.", fact: false, explain: "170–190 év a dokumentált maximum.", level: 2 },
    { id: 99, text: "Az 'OK' az 'oll korrect' rövidítése.", fact: true, explain: "1830-as újságírói tréfa.", level: 2 },
    { id: 100, text: "A Photoshopot egy nagy cég fejlesztette.", fact: false, explain: "Két testvér fejlesztette, az Adobe később licencelte.", level: 2 },
    { id: 101, text: "A Planck-állandó értékét mérés határozza meg.", fact: false, explain: "2019 óta definíció szerint rögzített.", level: 3 },
    { id: 102, text: "A Fermat-sejtést Fermat bizonyította be.", fact: false, explain: "Andrew Wiles bizonyította 1994-ben.", level: 3 },
    { id: 103, text: "Az összefonódás gyorsabb kommunikációt tesz lehetővé.", fact: false, explain: "No-communication theorem.", level: 3 },
    { id: 104, text: "A Bizánci Birodalom 1000 évvel élte túl a Nyugatrómai Birodalmat.", fact: true, explain: "476 → 1453.", level: 3 },
    { id: 105, text: "Gödel tétele szerint minden állítás bizonyítható.", fact: false, explain: "Vannak igaz, de nem bizonyítható állítások.", level: 3 },
    { id: 106, text: "Az entrópia fogalma csak a termodinamikában létezik.", fact: false, explain: "Shannon információelméletben is használja.", level: 3 },
    { id: 107, text: "Nagy Károly koronázása helyreállította a Nyugatrómai Birodalmat.", fact: false, explain: "Új császári cím volt, nem helyreállítás.", level: 3 },
    { id: 108, text: "A Higgs-bozont 2012-ben igazolták.", fact: true, explain: "CERN LHC.", level: 3 },
    { id: 109, text: "A Mongol Birodalom nagyobb volt, mint a Brit Birodalom.", fact: false, explain: "Brit Birodalom nagyobb volt, csak nem összefüggő.", level: 3 },
    { id: 110, text: "A Riemann-sejtést már bizonyították.", fact: false, explain: "Millenniumi probléma, máig nyitott.", level: 3 },
    { id: 111, text: "A Peano-axiómák a valós számokat definiálják.", fact: false, explain: "A természetes számokat definiálják.", level: 3 },
    { id: 112, text: "A weimari hiperinflációban óránként duplázódtak az árak.", fact: true, explain: "Napi 20% infláció → ~3,7 óránként duplázódás.", level: 3 },
    { id: 113, text: "A CRISPR-Cas9 nem természetes eredetű.", fact: false, explain: "Baktériumok immunrendszere.", level: 3 },
    { id: 114, text: "Turing egyedül, gépek nélkül törte fel az Enigmát.", fact: false, explain: "Bombe gépek, nagy csapat.", level: 3 },
    { id: 115, text: "A GPS működésében nincs relativitáselméleti korrekció.", fact: false, explain: "Gravitációs időtágulás miatt kell korrekció.", level: 3 },
    { id: 116, text: "A Monarchia azonnal hadat üzent a merénylet után.", fact: false, explain: "1 hónappal később, július 28-án.", level: 3 },
    { id: 117, text: "A sötét anyagot már közvetlenül detektálták.", fact: false, explain: "Csak közvetett bizonyítékok vannak.", level: 3 },
    { id: 118, text: "A görögtűz receptje ismert.", fact: false, explain: "A recept elveszett 1453 után.", level: 3 },
    { id: 119, text: "A Schrödinger-macska a koppenhágai értelmezést támogatja.", fact: false, explain: "Kritika volt, nem támogatás.", level: 3 },
    { id: 120, text: "A Bretton Woods-i rendszer a dollárt aranyhoz kötötte.", fact: true, explain: "1944–1971.", level: 3 },
    { id: 121, text: "A P vs NP probléma azt kérdezi, hogy minden NP probléma gyorsan megoldható-e.", fact: true, explain: "Polinomiális ellenőrzés vs megoldás.", level: 3 },
    { id: 122, text: "A Habsburgok 1273–1918 között megszakítás nélkül uralkodtak.", fact: false, explain: "Habsburg-Lotaringiai ág, megszakításokkal.", level: 3 },
    { id: 123, text: "A neutrínóknak nincs tömegük.", fact: false, explain: "Neutrínó-oszcilláció bizonyítja, hogy van.", level: 3 },
    { id: 124, text: "A Weimari alkotmány 48. cikkelyét nem használták fel.", fact: false, explain: "Hitler felhasználta a diktatúra kiépítéséhez.", level: 3 },
    { id: 125, text: "A Boltzmann-állandó × Avogadro-szám = gázállandó.", fact: true, explain: "R = k × Nₐ.", level: 3 },
    { id: 126, text: "A Rosetta-kő nem segített a hieroglifák megfejtésében.", fact: false, explain: "Három nyelven tartalmazta ugyanazt a szöveget.", level: 3 },
    { id: 127, text: "A fotonnak végtelen tömege lenne.", fact: false, explain: "Nyugalmi tömege nulla.", level: 3 },
    { id: 128, text: "Mária Terézia birodalma egységes maradt a háborúk után.", fact: false, explain: "Szilézia elveszett, háborúk Poroszországgal.", level: 3 },
    { id: 129, text: "Az indukció azt jelenti, hogy ha igaz 1-re, 2-re, 3-ra, akkor mindenre igaz.", fact: false, explain: "Bázislépés + indukciós lépés szükséges.", level: 3 },
    { id: 130, text: "A Trienti Zsinat indította el az ellenreformációt.", fact: true, explain: "1545–1563.", level: 3 },
    { id: 131, text: "A macska miau-t mond, a kutya vau-t.", fact: true, explain: "Alapvető állathangok.", level: 1 },
    { id: 132, text: "A banán éretten sárga.", fact: true, explain: "Éretlenül zöld.", level: 1 },
    { id: 133, text: "Egy hétnek 5 napja van.", fact: false, explain: "7 napból áll.", level: 1 },
    { id: 134, text: "A hal a vízben él és kopoltyúval lélegzik.", fact: true, explain: "Kopoltyúval veszi fel az oxigént.", level: 1 },
    { id: 135, text: "A Nap éjszaka süt.", fact: false, explain: "Nappal süt.", level: 1 },
    { id: 136, text: "Télen hó eshet, nyáron meleg van.", fact: true, explain: "Évszakok jellemzői.", level: 1 },
    { id: 137, text: "A pók 4 lábú.", fact: false, explain: "A pók 8 lábú.", level: 1 },
    { id: 138, text: "A répa narancssárga.", fact: true, explain: "Leggyakoribb fajta.", level: 1 },
    { id: 139, text: "A méhek mézet készítenek, a tehenek tejet adnak.", fact: true, explain: "Alapvető állati termékek.", level: 1 },
    { id: 140, text: "Egy évnek 10 hónapja van.", fact: false, explain: "12 hónapból áll.", level: 1 },
    { id: 141, text: "Egy pár cipőben 2 cipő van.", fact: true, explain: "A 'pár' két darabot jelent.", level: 1 },
    { id: 142, text: "A tűz forró, a jég pedig hideg.", fact: true, explain: "A tűz magas hőmérsékletű, a jég fagyott víz.", level: 1 },
    { id: 143, text: "A madarak úsznak, a halak pedig repülnek.", fact: false, explain: "A madarak repülnek, a halak úsznak.", level: 1 },
    { id: 144, text: "Piros és kék színt összekeverve lila színt kapunk.", fact: true, explain: "A két alapszín keveréke lila.", level: 1 },
    { id: 145, text: "Egy kockának 4 oldala van.", fact: false, explain: "Egy kockának 6 oldala van.", level: 1 },
    { id: 146, text: "A tehén és a ló is háziállat.", fact: true, explain: "Mindkettőt gyakran tartják gazdaságokban.", level: 1 },
    { id: 147, text: "Reggel a Nap nyugaton kel fel.", fact: false, explain: "A Nap keleten kel fel.", level: 1 },
    { id: 148, text: "A hó fehér színű, hideg időben esik.", fact: true, explain: "Télen, hidegben hullik.", level: 1 },
    { id: 149, text: "Egy órának 100 perce van.", fact: false, explain: "Egy órának 60 perce van.", level: 1 },
    { id: 150, text: "Az alma és a körte is gyümölcs.", fact: true, explain: "Mindkettő fán terem.", level: 1 },
    { id: 151, text: "A kutya négy lábon jár, a madár pedig két lábon.", fact: true, explain: "A madarak két lábon állnak.", level: 1 },
    { id: 152, text: "A karácsonyt nyáron ünnepeljük.", fact: false, explain: "Télen, december 25-én.", level: 1 },
    { id: 153, text: "A citrom íze savanyú.", fact: true, explain: "Magas citromsav-tartalom miatt.", level: 1 },
    { id: 154, text: "Egy kéznek 3 ujja van.", fact: false, explain: "Egy kéznek 5 ujja van.", level: 1 },
    { id: 155, text: "A víz megfagyva jéggé, felforralva gőzzé válik.", fact: true, explain: "Halmazállapot-változás.", level: 1 },
    { id: 156, text: "A béka a szárazföldön és a vízben is képes élni.", fact: true, explain: "A békák kétéltűek.", level: 1 },
    { id: 157, text: "Egy futballcsapatban egyszerre 20 játékos van a pályán egy csapatból.", fact: false, explain: "Egy csapatból 11 játékos van a pályán.", level: 1 },
    { id: 158, text: "A tavasz és az ősz is egy-egy évszak.", fact: true, explain: "A négy évszak részei.", level: 1 },
    { id: 159, text: "A repülőgép a vízen közlekedik, a hajó pedig a levegőben.", fact: false, explain: "Fordítva: repülő a levegőben, hajó a vízen.", level: 1 },
    { id: 160, text: "Egy pizzának lehet több szelete is.", fact: true, explain: "A pizzát felszeletelik.", level: 1 },
    { id: 161, text: "A répa és a krumpli is a föld alatt nő.", fact: true, explain: "Mindkettő gyökérzöldség.", level: 1 },
    { id: 162, text: "Egy évszaknak 6 hónapja van.", fact: false, explain: "Egy évszak 3 hónapból áll.", level: 1 },
    { id: 163, text: "A méh megcsípheti az embert, ha megzavarják.", fact: true, explain: "Védekezésként csíp.", level: 1 },
    { id: 164, text: "Egy autónak 6 kereke van.", fact: false, explain: "Egy autónak 4 kereke van.", level: 1 },
    { id: 165, text: "A Föld a Nap körül kering.", fact: true, explain: "Éves periódusban.", level: 1 },
    { id: 166, text: "Egy nap 48 óráig tart.", fact: false, explain: "Egy nap 24 órás.", level: 1 },
    { id: 167, text: "Az oroszlán és a tigris is macskaféle.", fact: true, explain: "Mindkettő nagytestű ragadozó.", level: 1 },
    { id: 168, text: "Az esernyőt eső ellen használjuk, a napszemüveget pedig sötétben.", fact: false, explain: "A napszemüveg napos időben kell.", level: 1 },
    { id: 169, text: "A hangya és a katicabogár is rovar.", fact: true, explain: "Mindkettő 6 lábú.", level: 1 },
    { id: 170, text: "Éjszaka a Holdat és a csillagokat láthatjuk.", fact: true, explain: "Derült időben jól láthatók.", level: 1 },
    { id: 171, text: "A 'Cogito, ergo sum' Descartes latin művében jelent meg először.", fact: false, explain: "Először franciául: 'Je pense, donc je suis'.", level: 3 },
    { id: 172, text: "A Bayes-tétel a feltételes valószínűségeket írja le.", fact: true, explain: "P(A|B) = P(B|A)·P(A)/P(B).", level: 3 },
    { id: 173, text: "A Nikaiai Zsinat célja a Biblia kánonjának meghatározása volt.", fact: false, explain: "Ariánus vita lezárása volt a cél.", level: 3 },
    { id: 174, text: "A termodinamika második főtétele szerint egy zárt rendszer entrópiája nem csökkenhet.", fact: true, explain: "Csak nőhet vagy állandó maradhat.", level: 3 },
    { id: 175, text: "A Habsburgok házasságpolitikával növelték hatalmukat.", fact: true, explain: "Bella gerant alii, tu felix Austria nube.", level: 3 },
    { id: 176, text: "A Voyager–1 ma is működik és adatokat küld.", fact: true, explain: "1977-ben indult, 2012 óta csillagközi térben.", level: 3 },
    { id: 177, text: "A jakobinusok nevüket egy kolostorról kapták.", fact: true, explain: "Domonkos (jakobinus) kolostor Párizsban.", level: 3 },
    { id: 178, text: "Watson és Crick egyedül fedezték fel a DNS szerkezetét.", fact: false, explain: "Franklin felvételeire támaszkodtak.", level: 3 },
    { id: 179, text: "Nagy Sándor birodalma egységes maradt halála után.", fact: false, explain: "Feldarabolódott: Ptolemaida, Szeleukida, Antigonida.", level: 3 },
    { id: 180, text: "A korreláció okozati összefüggést jelent.", fact: true, explain: "Nem bizonyít ok-okozatot.", level: 3 }
];
